name: Python 3.9 app. test with github Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run:
        make install
    - name: Lint with Pylnt
      run:
        make lint
    - name: Test wth Pytest
      run:
        make test
    - name: Format code with Python
      run:
        make format
